# test of policy scan issue importer
 
name: Policy scan Issue importer (assumes build)

# on: [push, pull_request, workflow_dispatch]
#  #on: gollum          # sort of a dummy to prevent this from running
on: push
jobs:
  get-policy-flaws:
    runs-on: maven-latest
    container: 
      image: veracode/api-signing:latest
    steps:
      # Note: this will likely fail if there are more than 500 flaws, due to Veracode results limiting
      #   (would need a more elaborate method)
      - name: Break the Build
        run: |
          export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          ./veracode package -s . -a 
